version: "3.8"

volumes:
  pgdata:

services:
  db:
    build:
      dockerfile: docker/postgres/Dockerfile
      context: .
    environment:
      POSTGRES_DB: "${DATABASE_HOST}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5435:5432
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    environment:
      DEPLOYMENT_COLOR: "${IDLE_COLOR}"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT} --settings=djangoprod.settings"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/code
    depends_on:
      - db