version: "3.8"

services:
  db:
    build:
      dockerfile: docker/postgres/Dockerfile
      context: .
    environment:
      POSTGRES_DB: "${DATABASE_HOST}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    environment:
      DEPLOYMENT_COLOR: "${IDLE_COLOR}"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${PORT} --settings=djangoprod.settings"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/code
    depends_on:
      - db
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com

volumes:
  pgdata: