version: "3.8"
services:
  api:
    build: .
    command: sh -c "python manage.py migrate && gunicorn --env DJANGO_SETTINGS_MODULE=djangoprod.settings-prod djangoprod.wsgi -b 0.0.0.0:${PORT}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/code