api:
  insecure: true
  dashboard: true
  debug: true


log:
  level: DEBUG


providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: main
    exposedByDefault: true
  file:
    filename: "/dynamic.yaml"


entryPoints:
  web:
    address: ":80"
  web-secured:
    address: ":433"


certificatesResolvers:
  mytlschallenge:
    acme:
      tlsChallenge: true
      email: "mopitz199@gmail.com"
      storage: "/letsencrypt/acme.json"

  
http:
  middlewares:
    redirect:
      redirectScheme:
        scheme: https