# Generated by Django 3.1.5 on 2021-01-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_auto_20210105_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to='media/'),
        ),
    ]
